version: '3.7'
services:
#React Service
  react:
    container_name: react-container 
    build: ./react
    ports:
      - '80:80'
    environment:
      - BASE_URL=http://localhost:8000/api/winners/
#NGINX Service
  nginx:
    container_name: nginx-container
    image: nginx:alpine
    tty: true
    ports:
      - "8000:80"
    volumes:
      - ./src:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-fpm
    networks:
      - backend
  
#PHP-FPM Service
  php-fpm:
    container_name: php-container
    build: ./php-fpm
    volumes:
      - ./src:/var/www
      - ./php-fpm/www.conf:/usr/local/etc/php-fpm.d/www.conf
    ports:
      - "9000:9000"
    depends_on:
      - mysqlmaster
    tty: true
    environment:
      APP_KEY: base64:egptnpAr3lYfETA6QSCSdaoA2Fiii9dJCPE1yjGy86Y=
    networks: 
      - backend
  
  migration:
    container_name: migration-container
    build: ./migration
    tty: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - backend

#MYSQL Service    
  mysqlmaster:
      image: mariadb:latest
      container_name: mariadb-container
      restart: unless-stopped
      tty: true
      ports:  
        - "3306:3306"
      environment:
        MYSQL_DATABASE: EurosongFestival
        MYSQL_USER: homestead
        MYSQL_PASSWORD: secret
        MYSQL_ROOT_PASSWORD: root
        SERVICE_NAME: mysql
      volumes:
        - ./database/data/mysql-master:/var/lib/mysql/
        - ./database/config/mysql-master:/etc/mysql/conf.d/
      networks:
        - backend
        - database

  mysqlslave:
      image: mariadb:latest
      environment:
        MYSQL_ROOT_PASSWORD: root
      volumes:
        - ./database/data/mysql-slave:/var/lib/mysql
        - ./database/config/mysql-slave:/etc/mysql/conf.d/
      networks:
        - database
      
  mysqlconfigure:
    image: mariadb:latest
    environment:
      - "MYSQL_SLAVE_PASSWORD=root"
      - "MYSQL_MASTER_PASSWORD=root"
      - "MYSQL_ROOT_PASSWORD=root"
      - "MYSQL_REPLICATION_USER=repl"
      - "MYSQL_REPLICATION_PASSWORD=repl"
    volumes:
      - ./database/config/mysql_connector.sh:/tmp/mysql_connector.sh
    command: /bin/bash -x /tmp/mysql_connector.sh
    networks:
      - database


networks: 
  backend:
  database:
